# Generated by Django 3.0.5 on 2020-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='summary',
            field=models.CharField(default='', max_length=120, verbose_name='Summary'),
        ),
    ]
