# Generated by Django 3.0.5 on 2020-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickgenerator', '0002_effect_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
    ]
